Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/FrozenStringLiteralComment:
  Enabled: false
ClassAndModuleChildren:
  EnforcedStyle: compact
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'spec/spec_helper.rb'
    - 'cookbook_client.gemspec'
    - 'Rakefile'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']
